const INITIAL_PROPERTIES = [
	{ value: 1, image_url: "" },
	{ value: 2, image_url: "" },
	{ value: 3, image_url: "" },
	{ value: 4, image_url: "" },
	{ value: 5, image_url: "" },
	{ value: 6, image_url: "" },
	{ value: 7, image_url: "" },
	{ value: 8, image_url: "" },
	{ value: 9, image_url: "" },
	{ value: 10, image_url: "" },
	{ value: 11, image_url: "" },
	{ value: 12, image_url: "" },
	{ value: 13, image_url: "" },
	{ value: 14, image_url: "" },
	{ value: 15, image_url: "" },
	{ value: 16, image_url: "" },
	{ value: 17, image_url: "" },
	{ value: 18, image_url: "" },
	{ value: 19, image_url: "" },
	{ value: 20, image_url: "" },
	{ value: 21, image_url: "" },
	{ value: 22, image_url: "" },
	{ value: 23, image_url: "" },
	{ value: 24, image_url: "" },
	{ value: 25, image_url: "" },
	{ value: 26, image_url: "" },
	{ value: 27, image_url: "" },
	{ value: 28, image_url: "" },
	{ value: 29, image_url: "" },
	{ value: 30, image_url: "" },
];

const INITIAL_CURRENCIES = [
	{ value: 0, image_url: "" },
	{ value: 0, image_url: "" },
	{ value: 2000, image_url: "" },
	{ value: 2000, image_url: "" },
	{ value: 3000, image_url: "" },
	{ value: 3000, image_url: "" },
	{ value: 4000, image_url: "" },
	{ value: 4000, image_url: "" },
	{ value: 5000, image_url: "" },
	{ value: 5000, image_url: "" },
	{ value: 6000, image_url: "" },
	{ value: 6000, image_url: "" },
	{ value: 7000, image_url: "" },
	{ value: 7000, image_url: "" },
	{ value: 8000, image_url: "" },
	{ value: 8000, image_url: "" },
	{ value: 9000, image_url: "" },
	{ value: 9000, image_url: "" },
	{ value: 10000, image_url: "" },
	{ value: 10000, image_url: "" },
	{ value: 11000, image_url: "" },
	{ value: 11000, image_url: "" },
	{ value: 12000, image_url: "" },
	{ value: 12000, image_url: "" },
	{ value: 13000, image_url: "" },
	{ value: 13000, image_url: "" },
	{ value: 14000, image_url: "" },
	{ value: 14000, image_url: "" },
	{ value: 15000, image_url: "" },
	{ value: 15000, image_url: "" },
];

const COINS = {
	1000: {
		value: 1000,
		image_url: "https://www.ultraboardgames.com/for-sale/gfx/forsale8.jpg",
	},
	2000: {
		value: 2000,
		image_url: "https://www.ultraboardgames.com/for-sale/gfx/forsale9.jpg",
	},
};

module.exports = { INITIAL_PROPERTIES, INITIAL_CURRENCIES, COINS };
